language: node_js
node_js:
- 5.8
- 4.4
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: xKFhfcfGosGDeQe0HkV/IMETV6skg9VAFxBOny+tRNn2holTT06hKGSuNIymnuvg9OSSlZtqoiU7wt0Hz0uoK8X/5QuIeDjWEWcz+gxdJafe11cxCieZT1anZuLNdfZV2R4EfVVuewLPRm+khJ8BKi+DX8w4U/uYbuvm3NrCl/pQ8nHtb1EelGgEqv0/Tc6y6Ii4JBnr+23ytmZxq0HByk1sFKfoRC6fLP5jr2hs9d0SJJIO9VcAe98ZTK2RCgB4IeXVa5j9mse3rhTkuFTxNzqPx/N7uNUnAiZy89IN3p2SfTQL0jD6UX3wb5bdjApdi0dwVpN+XjbjS/r/P1LaA5qMyp5KsaCCl1n7wuawWgdoqeSiNSPG4a+rjbWz+AdLRj2UB2u6/cH1rjb5gobrf/YhcWwBMy6m7Vq9wuyE/SN0yEt8kJboCjIX5ps3i9orgHlSOv6pJuURvRWfj+GdaNbjC1u4lUp9F/n1MH+RBtJyljqvWrC+rLiYjh8hvqw5BkLNENomkQ8RfkHZf9k0axzfJipqeiGcL4OnYpkJE2ktur6rZpJQkHJkpTACZV96J6+IrNmfIyJj+eY0HTKWvG3TZIBxlizi8kmv2KZ9vV3Hc3Qrq93lyiA4Bf2ZNppJTMI7660r3nBOce0U35tebChDLPSgpekUcT+SobtLhdg=
